### ISSUE TITLE
transfer to purescript-contrib

### ISSUE THREAD

**Issue by jamesdbrock** [purescript-contrib/purescript-arraybuffer#30]
* [x] Run contrib-updater.
* [x] Change default branch to `main`.
* [x] Confirm CI is working.
* [x] Delete `uint` and `float32` additions in `package.dhall`.

https://github.com/purescript-contrib/governance/blob/main/library-guidelines.md

**Comment by JordanMartinez** [comment]
I've changed the default branch to `main`.
