### ISSUE TITLE
Slice and subArray documentation reversed

### ISSUE THREAD

**Issue by jacereda** [purescript-contrib/purescript-arraybuffer#49]
Aren't the comments for `slice` and `subArray` reversed?

https://github.com/purescript-contrib/purescript-arraybuffer/blob/51271ec72102f4dcb7064f4d9220700ebf5bd8f2/src/Data/ArrayBuffer/Typed.purs#L26

**Comment by jamesdbrock** [comment]
Yeah I think you're right.
