### ISSUE TITLE
Version 1.0.1 should be 2.0.0

### ISSUE THREAD

**Issue by PipocaQuemada** [purescript-contrib/purescript-arraybuffer#5]
[Bower components should use semvar](https://bower.io/docs/creating-packages/).  In semvar, 1.0.0 => 1.0.1 indicates a patch update - a backwards compatible bug fix.  Changing type signatures is a non-backwards compatible change, so the major version should have been bumped to help avoid type errors when compiling old code.

**Comment by jacereda** [comment]
Tagged as v2.0.0, thanks.
