### ISSUE TITLE
The last published release is 2.0.0, but bower.json is updated to 3.0.0

### ISSUE THREAD

**Issue by PipocaQuemada** [purescript-contrib/purescript-arraybuffer#7]
Currently, the latest published tag is v2.0.0 - see https://github.com/jacereda/purescript-arraybuffer/tags to verify.  However, the dependencies have been updated since then - see e.g. https://github.com/jacereda/purescript-arraybuffer/blob/61a273192b889784ddc1c18ad4ad9dd7403249e2/bower.json

Did you mean to publish a new release compatible with 0.10?  Since git tags aren't pushed by default, you might have accidentally forgotten to `git push origin v3.0.0`.

**Comment by jacereda** [comment]
I was probably waiting for -uint to update its dependencies so I could get rid of the "resolutions" in bower.json, but somehow I forgot about it at some point.

Thanks!
