### ISSUE TITLE
Mutability of types in Data.ArrayBuffer.ArrayBuffer

### ISSUE THREAD

**Issue by sgronblo** [purescript-contrib/purescript-arraybuffer#8]
Shouldn't some of the functions in Data.ArrayBuffer.ArrayBuffer (create in particular, but potentially others too) be Eff computations?

**Comment by jacereda** [comment]
Yes. If you haven't fixed it I can try in a couple of days.

**Comment by sgronblo** [comment]
Haven't fixed. I'm not too used to working with PS yet.

**Comment by jacereda** [comment]
I have committed the proposed API to https://github.com/jacereda/purescript-arraybuffer/tree/effectful

If you can think of any improvement just let me know.

**Comment by jacereda** [comment]
Just tagged a new version.
